### ISSUE TITLE
Importing preexisting Content Models, Entries and Assets

### ISSUE THREAD

**Issue by JSkally** [contentful-labs/contentful.py#5]
is there some way to do this like:

`client.fetch('content_types').all()`
or
`client.fetch('entries').all()`
or
`client.fetch('assets').all()`

that returns an array of the preexisting content types with their fields and such?

**Comment by tomxor** [comment]
Yap, as described in the documentation you need to pass the class to the `fetch()` method, e.g.:

``` python
client.fetch(Asset).all()
client.fetch(Entry).all()
client.fetch(ContentType).all()
```

**Comment by tomxor** [comment]
@JSkally please comment on whether or not your issue is resolved.

**Comment by JSkally** [comment]
@tomxor wouldn't that require me to setup a class before. Suppose I want to get all the content types beforehand like in the Android SDK where it sends over each content type as an object which would then allow me to setup the necessary classes.

**Comment by tomxor** [comment]
I'm not sure if I completely understand what you mean, could you provide an example?

**Comment by tomxor** [comment]
Or perhaps I do :) Classes: `Asset`, `ContentType` and `Entry` are built-in the SDK, you simply need to import those first, e.g:

``` python
from contentful.cda.resources import ContentType

for ct in client.fetch(ContentType).all():
  print(ct.fields)
```

Check out the [official documentation](http://contentful.github.io/contentful.py/package.details.html#module-contentful.cda.resources) for the `resources` module.

**Comment by JSkally** [comment]
@tomxor PERFECT thanks

**Comment by tomxor** [comment]
Sure, glad I could help.
